### ISSUE TITLE
feature/authentication 

### ISSUE THREAD

**Issue by WittmannD** [WittmannD/dictionary-app#1]
### Purpose description

Create a user authentication module for auth with credentials (email, password) and using third-party authentication providers.

Users should be able to choose between authentication methods, and create a new account. If they have forggeten their password, they should be able to reset it via email. Also after creating a new account users have to verify their email. Confirmation link in the email should become invalid if it has expired, and users should reinitiate sending of confirmation letter.

As a third-party auth provider use Google OAuth API

Application should have at least 2 types of jwt - verification token and refresh token. Both must be returned after a login request

See [out of the box solution](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html) by `djangorestframework-simplejwt`.

### Tasks
- [ ] Customize `djangoresframework-simplejwt` as required. see [docs](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html)
- [ ] Configure SMTP email provider (for dev purpose can be used smtp.gmail.com and any google account)
- [ ] Email confirmation logic
- [ ] Password reset logic
- [ ] Google auth strategy
- [ ] Create a basic ui for the login and registration page.

**Comment by EstaFaith** [comment]
UPD: authentication only with Google
