### ISSUE TITLE
feature/user-module

### ISSUE THREAD

**Issue by WittmannD** [WittmannD/dictionary-app#2]
### Purpose description
Create a user module. This module should contain the main logic that is related to the user, include endpoints for getting, changing user profile fields.

### Tasks
- [ ] User db model
- [ ] User model view (controller)
- [ ] Ability to change the user's password via email confirmation
- [ ] Basic user profile page ui
