### ISSUE TITLE
feature/frontend-project-configuration

### ISSUE THREAD

**Issue by WittmannD** [WittmannD/dictionary-app#3]
### Purpose description
Configure the frontend project

### Tasks
- [x] Build a new Next.js application
- [x] Basic environment configuration for the project
- [x] Сonfigure project build in docker compose
- [x] Set up precommit hooks for frontend project
