### ISSUE TITLE
feature/dictionary

### ISSUE THREAD

**Issue by WittmannD** [WittmannD/dictionary-app#4]
### Purpose description
Implement dictionary business logic. 
Create a module with REST endpoints for geting information on the translated word. The endpoint path to get the translation of a word should look something like this:
`dictionary/languages` - to get available languages
`dictionary/{srcLng}/words/{word}` - to get word details
`dictionary/{srcLng}/words/{word}/definitions` - to get word definitions
`dictionary/{srcLng}/words/{word}/modifications` - to get word modifications (like verb forms, infinitives, case declensions, etc)
`dictionary/{srcLng}/words/{word}/synonyms` - to get word synonyms
`dictionary/{srcLng}/words/{word}/translations/{destLng}` - to get translation

where `srcLng` - source langauge code, `destLng` - language code for translation, `word` - word text

### Tasks
- [ ] Create dictionary entities models
- [ ] Languages controller
- [ ] Word definitions controller
- [ ] Translation controller
- [ ] Word modifications controller
- [ ] Word synonyms controller
